SET NAMES 'utf8';

CREATE TABLE `vehicles` (
  `id` int(11) NOT NULL,
  `type` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

CREATE TABLE `journeys` (
  `id` int(11) NOT NULL,
  `vehicle` int(11) NOT NULL,
  `country` varchar(100) NOT NULL,
  `description` text,
  `departure` date NOT NULL,
  `capacity` int(11) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;


INSERT INTO journeys(`id`, `vehicle`, `country`, `description`, `departure`, `capacity`) VALUES
(1, 3, 'Horvátország', 'A meseszép horvát tengerpart 177 kilométer hosszan nyúlik el, de ha a szigetek (1185, ebből 66 lakott) kerületét is figyelembe vesszük, összesen 5835 km, így igen nehéz kiválasztani, merre is induljunk el. A horvát Adria-part karsztos part, a világ legjobban tagolt tengerpartja. Idegenforgalmi szempontból a horvát Adria alapvetően három nagyobb részre osztható: Isztriai-félsziget, Kvarner-öböl és Dalmácia tengerpartja. Itt mindenki megtalálja a magának tetsző partot: homokos, kavicsos, sziklás. A kavicsos, sziklás partszakaszokon mindenképpen ajánlott strandcipő használata. Kisgyerekekkel elindulva a legközelebb Crikvenicánál üdülhetünk homokos partszakaszon, de Medulinnál, Loparnál, Ninnél valamint Omisnál, Brac szigeten vagy akár Krk szigeten is találunk homokos partokat. \r\n\r\nÉld át a pezsgő mediterrán életet és látogass meg olyan városokat, mint pl Rovinj, Pula, Zadar, Biograd, Vodice, Split, Hvar vagy Makarska. Ha kevésbé pezsgő, de szép középkori, mediterrán városban nyaralnál Horváthországban, akkor Porec, Novigrad, Krk, Rab, Trogir illetve a Brac sziget egyaránt jó választás lesz. \r\n\r\nA horvátországi nyaralások legnagyobb kincse a tenger alatti világ. Olyan tiszta a tengervíz, hogy komoly búvártudás nélkül, akár csak egy búvárszemüveggel is felfedezhetjük gazdag élővilágát. \r\n\r\nGasztronómiája főként fűszeres ételeket tartalmaz, sok hal, és sajt kerül az asztalukra. Nyaralásod alkalmával kóstold meg a húsos-sajtos lepényt, a bureket, a rákból készült prstacit, és a dalmát rizses halat, a brodetet. Kóstolj mandulát, fügét, szőlőt, melyek íze páratlan. Egyedülálló a szél szárította dalmát sonka. Kísérőnek fogyassz a sziget vörös és fehér boraiból, melyek közül némelyik a világ tíz legjobb bora közé tartozik. Horvátország nemcsak a tengerpartja miatt lehet érdekes számunkra, utazzunk el a A Plitvicei-tavak Nemzeti Parkhoz, mely 1949 óta nemzeti park, 1979-től a világörökség része. ', '2022-04-27', 0),
(2, 2, 'Görögország', 'Görögország olyan gazdag kulturális örökséggel és természeti kincsekkel rendelkezik, hogy úgy érezzük, soha nem fogjuk tudni teljesen felfedezni, akárhányszor is látogatunk el ide. Végtére is, ez az egyik oka annak, hogy a világ top 20 turisztikai célpontja közé bekerült. Minden nyáron tömegek látogatnak el ebbe a csodálatos országba, hogy felfedezzék történelmi kincseit és csodálatos tájait. \r\nPartvonala erősen tagolt, a leghosszabb európai partszakasszal büszkélkedhet, 1300 szigetéből 170 lakott. Az ország három földrajzi régióra oszlik: a szárazföldre, a szigetekre és a Peloponnészoszi félszigetre. Az év több mint 250 napján süt a nap összesen több mint 3000 órát. Nincs olyan pontja az országnak, ami 140 km-nél távolabb lenne a tengertől. Görögország Európa, Ázsia és Afrika találkozásánál fekszik. Területén már a bronzkortól egész Európa fejlődését meghatározó kultúrák alakultak ki. A virágzó hellén Birodalmat az egyre erősödő Róma hódította meg, majd a Római Birodalom kettéválása után a 15. századig a Bizánci Császárság része volt, a, aztán a török hódítás áldozatául esett, és az Oszmán Birodalom uralma alá került. Ez a hosszú, több mint 400 éves időszak hozta létre gazdag építészeti kincseit, mint például az Akropolisz, mely a világ 7 csodájának egyike. \r\nGörögország a demokrácia, a nyugati filozófia, az olimpiai játékok, a matematika és a kultúra bölcsője. Látnivalók a teljesség igénye nélkül: Athén és az Akropolisz, Meteorák, Olümpia, Krétán, a Knósszoszi Palota, a Samaria szurdok és Rodoszon a lindoszi fellegvár. A legkedveltebb görög szigetek: Korfu, Kréta, Rodosz, Zakynthosz és Santorini. Nyaralásod során feltétlenül fedezd fel a görög konyha ízvilágát. Egyészséges mediterrán konyhát vezetnek, mely sok gyümölcsöt, friss zöldséget, tenger gyümölcseit és halat tartalmaz. Ki ne ismerné a híres görög ételeket, mint a gyros, souvlaki vagy muszaka. Ülj be egy hangulatos tavernába és az ebéd mellé igyunk ouzot, mely a görögök nemzeti itala. Ha koccintasz, akkor mondd azt, hogy „Gia mas”. \r\nPár érdekesség Görögországról: \r\nIkaria szigetén az emberek 10 évvel tovább élnek - átlagban 90 éves korukig -, mint bárhol máshol a világon, köszönhetően egészséges életmódjuknak és stresszmentes életvitelüknek. \r\nGörögország területén található a világ legtöbb régészeti múzeuma. \r\nA görög az egyik legrégebben beszélt nyelv a világon. \r\nA görög zászló kilenc kék-fehér vízszintes csíkot tartalmaz, a bal felső sarokban található kereszt szimbolizálja az ország vallását, az ortodox hitet. A kilenc vízszintes sáv a Szabadság vagy Halál nemzeti mottó kilenc szótagára utal. Más elgondolás szerint a kék Görögország tengerét és égboltját, míg a fehér a szabadságharc tisztaságát jelképezi. \r\nAz újszülöttek nem születésükkor kapnak keresztnevet, hanem első születésnapjuk körül, amikor megkeresztelik őket. \r\nMindezek miatt egyszer mindenkinek látni kell Görögországot és szigeteit! ', '2022-05-01', 54),
(3, 1, 'Egyesült Arab Emirátusok', 'Dubajnak gazdag története van, és az Egyesült Arab Emírségek kultúrája lenyűgöző, ha minden aranyat lekarcolsz. Nem számítottál erre? Haladjon a Dubai Creek szélén, a város eredeti szívében, ahol a Közel-Kelet szerte a kereskedők elcsalogatják áruikat. Itt vigyázhat az iráni türkiz csecsebecsékre, ománi ezüst kincsekre és Szaúd-Arábiából származó érmékre. Még egy látványos, az aranynak szentelt souk található - érdemes megnézni, akkor is, ha nem vásárol.', '2022-04-17', 114),
(4, 2, 'Törökország', 'Az országot északról a Fekete-tenger, délről a Földközi-tenger, míg nyugatról az Égei-tenger határolja. Ezek együttesen 8000 kilométer hosszú tengerparti szakaszt kínálnak a természeti kincseknek, strandoknak, szálláshelyeknek, gasztronómiai létesítményeknek. Legnépszerűbb strandjai a Földközi-, és Égei-tenger partjain találhatóak. A 1600 kilométer hosszú mediterrán tengerpartot, Török Riviérának vagy türkiz partnak neveznek. Nappal élvezd a napsütést, a tenger hullamait, míg napnyugta után éld át a dinamikus és színes éjszakai életet. Az élő zenétől, a tengerre néző koktélbárokon át, az éjszakai klubokig megtalálja mindenki a maga kikapcsolódási formáját. \r\nSzámos útvonalnak ad otthont, ahol a természet és a történelem együtt táncol. Szélben gazdag régiók, egyedi öblök, védett kikötők, tengerparti városok, várják a vitorlázni, hajózni és sportolni vágyókat. Légy részese a Boszporusz tengeri forgalmát megállító nemzetközi vitorlás esemény egyikének. Csodáld meg, és mélyítsd el ismereteid az országban található 18 UNESCO világörökségről, melyek egyaránt természeti és kulturális jelentőségűek is. Szinte mindegyik régió egyedi, saját gasztroélményt kínál, hiszen a török konyha az egyik leggazdagabb és legváltozatosabb a világon. Mind csak arra vár, hogy felfedezzék őket! Vásárolj dizájner ruhát, regionális finomságokat, egyedi kézműves termékeket és még sok mást. A hagyományostól, a szabadtéri piacokon, a fedett bazárokon, a luxus bevásárlóközpontokon át, mindenki megtalálja a számára megfelelő helyszínt. Egészítsd ki utazásod wellness-élménnyel. Törökország világszínvonalas termálforrásai és gyógyfürdői lehetővé teszik a fizikai és lelki feltöltődést, terápiás vizei és speciális gyógykezelései révén. A török hammamok kiemelkedő helyet foglalnak el az egészség-, és wellness-turizmusban, míg az úgy nevezett mediterrán étrendet a világ egyik legegészségesebbének tartanak. \r\nA hit bölcsője! Az ókori templomoktól a modern mecsetekig, vallási helyszíneinek története hosszú évszázadokra nyúlik vissza. Törökországban a vallási turizmus nagyon jelentős, ezért utazásod elött győződj meg az általános viselkedési szabályokról. A népeség majdnem egésze iszlám vallást követ, melyben a modernizáció már felütötte fejét, de egyes hagyományos elemek mai napig erősen jelen vannak. Éppen ezrért, kerüld a helyiek vallásával, politikájával kapcsolatos negatív véleményformálást. Pároknak javasolt a szolid, visszafogott viselkedés nyilvános helyeken, a nőknek a hosszú ruházat, míg a mecsetekbe látogatáskor a cipő levétele. \r\nA napsütés szinte egész évben garantált, ezáltal a téli időszakban is megfelelő úti cél. Földközi, - és Égei-tenger partvidékein az éghajlat mediterrán, mely meleg száraz nyarakkal, és mérsékelten meleg, esős telekkel párosul. A Fekete-tenger térségét ugyan szintén meleg, de enyhébb esős nyár, és hűvös tél jellemzi, így az utazás júliusban és augusztusban ajánlott. ', '2022-04-20', 72),
(5, 1, 'Maldív szigetek', 'Képeslapra illő tengerpari villák, türkizkék tenger, vakítóan fehér homokos strandok, csodás naplementék írják le ezt a paradicsomi helyet. A Maldív-szigetek nagyon népszerű célpont a nászutasok körében, de a kalandot keresők is szívesen felfedezik a tenger szépségét egy könnyű búvárkodás, sznorkelezés vagy szörfözés alkalmával. A világ korallzátonyinak 5%-a itt található, rendkívül színes vízi élővilággal. Habár csak mintegy félmillió ember lakja, kultúrája mégis rendkívül változatos, köszönhetően a hódító népeknek. Az ország földrajzi elhelyezkedése miatt az emberek és kultúrák olvasztótégelye volt. A lakosság egyharmada él a sziget fővárosában, Malén, a többiek elszórtan a 200 szigeten.\r\n\r\nA maldívok megélhetése hagyományosan a tengertől függött, a halászat volt a fő táplálékforrás, mely továbbra is jelentősen hozzájárul a gazdasághoz, de mára a turizmus lett a fő bevételi forrás. A hajókészítés mesterei. A hagyományos Maldív hajó, a dhoni, mely évszázadok alatt nyerte el mai formáját, alkalmazkodva a tenger szabta feltételeknek. A kézműves mesterségek generációról generációra szálltak, gazdag kínálatot mutatnak: lakkozott fa díszek, finoman szőtt nádszőnyegek, korall faragványok. A luxus szállások közül mindenki megtalálja a kedvére valót: választhatunk tenger fölé nyúló üvegpadlós bungalót, víz alatti szállást vagy a hihetetlenül gyönyörű üdülőhelyeket. ', '2022-04-13', 164),
(6, 1, 'Egyiptom', 'Az ókori Egyiptom a civilizáció bölcsője, mely olyan nevekkel, mint Ramszesz, Nefertiti és Tutanhamon, valamint olyan helyekkel, mint a Gízai nagy piramisok és a Szfinx vésődött a művészetben, az irodalomban és a népi kultúrában. Utazz a lélegzetelállító templomok, piramisok, síremlékek és a lenyűgöző műalkotások valamelyikéhez. Mind ezekkel egybeolvadva találod a modern Egyiptom egyedülálló szeleteit, gondolva itt Kairó és a nagyobb városok felhőkarcolóira, luxus szállodáira, éttermeire, illetve üzleteire és bevásárlóközpontjaira. \r\n\r\nKaland a sivatag mélyén. Sivatagi szafarik, quadozás a Keleti Sivatagban, túrázás és lovaglás a Sinai-hegységben vagy táborozás a Fehér Sivatagban, mind-mind életre szóló élménnyel gazdagítanak. Fedezd fel a váratlant, és merülj egyiptomi tengereibe, melyek feltárják a víz alatti élőlények és kincsek rengetegét. Búvárkodj a német tengeralattjáró-, vagy a napóleon kori hadihajó-roncs között, válaszd a korallzátony-búvárkodást a Vörös-tengerben vagy a Földközi-tenger víz alatti romjainak megismerését, a fáraók aranykorától egészen Kleopátra uralkodásáig. Ha nem érdekel a merülés, csillapítsd felfedezésszomjad sárkány-szörfözéssel vagy vitorlázással a Nílus hullámain. \r\n\r\nA pihenés Egyiptomban könnyedén megy! Napozz a Vörös-tengeri Riviéra üdülőhelyein, mártózz meg a világhírű fürdők valamelyikében, sétálj az érintetlen tengerpartokon és kortyolj mellé teát a folyóparti éttermekben, golfozz, az eléd táruló csodálatos kilátásban. Az ökoturizmus egyik kiemelkedő helye, segíts fenntartani az egyiptomi természetvédelmi területeket, maradj az öko-páholyokban, nemzeti parkjait, természeti kincseit a kijelölt túraútvonalakon barangold be, annak érdekében, hogy a következő generációk is ugyanazokat a természeti csodákat élhessék majd át. ', '2022-04-25', 138),
(7, 4, 'Olaszország', 'Olaszország művészeti és kulturális öröksége az egyik legértékesebb a világon. A legtöbb UNESCO világörökségi helyszínnek otthont adó ország. Remekművek gazdag kombinációját kínálja, ötvözve benne a természetet, kultúrát, építészetet, az ókori görögöktől és rómaiaktól egészen napjainkig. Látogass el olyan világhírű múzeumokba, mint a firenzei Uffizi Galéria, a római Capitoline Múzeum vagy a milánói Brera Art Galéria. Olaszország minden formában a zene és művészet szinonimája. A hagyományos és kulturális események széles skáláját kínálja, az irodalmi fesztiválokon át egészen a karneválokig, melyek élettel töltik meg az egész év folyamán.', '2022-04-18', 86),
(8, 1, 'Dominikai Köztársaság', '... a leggyönyörűbb föld, amelyet emberi szem valaha látott.\r\n\r\n1492-ben Kolumbusz Kristóf fedezte fel a második legnagyobb és legváltozatosabb karibi országot a Dominikai Köztársaságot. E trópusi paradicsomot északról az Atlanti-óceán, délről pedig a Karib-tenger veszi körül. Megannyi gyönyörű természeti környezet, romantikus vízesések, lélegzetelállító partok, tengerparti hegyek, köztük megbújó idilli szálláshelyek. Ismerd meg az ország történelmét, múzeumok és kulturális élmények: zenei és művészeti fesztiválok közepette. Fedezd fel a dominikai kávé, csokoládé, rum és szivar adta élményt. Tökéletes választás a golf szerelmeseinek, hiszen 26 dizájner golfpálya örvendezteti meg az idelátogatókat, és ne feledd a romantika és esküvők kifogástalan helyszíne.\r\n1600 kilométeres partvonal mentén, égbe nyúló kókuszfákkal várnak, a végtelenbe futó fehér homokos strandok. Fürdőzz a világhírű 48 kilométeres Punta Cana szakaszán vagy a világranglistán szereplő Samaná strandjainak egyikén. Kikapcsolódásra hív az északi partszakasz a Playa Cabarete-től egészen a Playa Grande-ig. A karibi partra néző strandok egész éveben biztonságosak, azonban az északi parvidéki fürdőzés során, kövesd figyelemmel az aktuális időjárási viszonyokat. A vasárnapok az úgynevezett tengerparti napok a dominikaiak számára, hol a csobbanás és napozás, zenével és lakomával egészül ki. Természetesen a strandok lehetőséget nyújtanak a különböző vízi sportok kipróbálására is, ilyen a búvárkodás, szörfözés, wakeboardozás, snorkel, vitorlázás vagy a vízisí.\r\nA Dominikai Köztársaság sokszínű domborzata és változó éghajlata tökéletes környezetet teremt a több mint 6000, növény- és állatfajnak. 29 nemzeti parkja közül a legnagyobb a Jaragua Nemzeti Park, nem messze tőle találod az egyetlen felhőerdővel rendelkező Sierra de Bahoruco-t, a leglátogatottabb pedig a Los Haitises Nemzeti Park. A parkok, hegyvidékek némi menedéket nyújtanak a parti hőség után, és ideális terepei a sziklamászásnak, kerékpározásnak, szafari túráknak, siklóernyőzésnek vagy akár a vadvízi evezésnek. ', '2022-05-10', 72),
(9, 2, 'Spanyolország', 'Spanyolország felfedezése akár csak egy időutazás. Évszázadok és vegyes kultúrák hagyták lenyűgöző nyomaikat az ország területén. Itt találod Velázquez, Picasso, Dalí és Gaudí által készített remekműveket. Ismerd meg művészeti tárházát vezetett túrák során, olyan múzeumokban, mint a Prado vagy olyan palotákban, mint a granadai Alhambra. Élmények, melyek sokkal többet kínálnak, mint egy átlagos emlékmű látogatás! Fedezd fel a város szívét, sétálj a hangulatos utcákon, válj a helyiek mindennapi életének részesévé. \r\nMenekülj a mindennapokból a természetbe! Spanyolország csaknem 8000 kilométer hosszú tengerparttal büszkélkedhet. Utazz az apró halaszfalvak, vagy az északi part nagyvárosainak egyikébe. Itt találod a Baleár-szigetek türkizkék, érintetlen öblét, a Kanári-szigetek vulkanikus strandjait továbbá a Földközi-tenger finom homokos partszakaszát. Kapcsolódj ki a tengerparton, vitorlázz, halássz a kikötőben vagy tölts el egy csodálatos éjszakát a naplementében. Egyedi és sokszínű természeti helyek sorakoznak fel, mint például a Serra de Tramuntana hegylánc, a Teide Nemzeti Park vagy akár a Pireneusok, melyek az UNESCO világörökség részét képzik. Mindezek csodáját látnod kell!\r\n\r\nHagyj helyet a vásárlásnak bőröndödben! Hosszú sétálóutcák, bevásárlónegyedek, piacok, nemzetközi és helyi tervezők márkái, valamint egyedi kézműves termékek teszik lehetővé, hogy haza vidd magaddal a spanyol trend egy kis szeletét.', '2022-06-27', 18);


INSERT INTO vehicles(`id`, `type`) VALUES
(1, 'repülőgép'),
(2, 'busz'),
(3, 'autó'),
(4, 'vonat'),
(5, 'hajó ');

ALTER TABLE `journeys` ADD PRIMARY KEY (`id`), ADD KEY `journeys_vehicle_foreign` (`vehicle`);

ALTER TABLE `vehicles` ADD PRIMARY KEY (`id`);

ALTER TABLE `journeys` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

ALTER TABLE `vehicles` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

ALTER TABLE `journeys` ADD CONSTRAINT `journeys_vehicle_foreign` FOREIGN KEY (`vehicle`) REFERENCES `vehicles` (`id`);

COMMIT;
