// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _18_EF_EgyATobbKapcsolat;

#nullable disable

namespace _18_EF_EgyATobbKapcsolat.Migrations
{
    [DbContext(typeof(IskolaContext))]
    partial class IskolaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_18_EF_EgyATobbKapcsolat.Osztaly", b =>
                {
                    b.Property<int>("osztalyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("osztalyFonok")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("osztalyNev")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("osztalyId");

                    b.ToTable("Osztaly");
                });

            modelBuilder.Entity("_18_EF_EgyATobbKapcsolat.Tanulo", b =>
                {
                    b.Property<int>("tanuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("osztalyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("szuletesiDatum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("tanuloNev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("tanuloId");

                    b.HasIndex("osztalyId");

                    b.ToTable("Tanulo");
                });

            modelBuilder.Entity("_18_EF_EgyATobbKapcsolat.Tanulo", b =>
                {
                    b.HasOne("_18_EF_EgyATobbKapcsolat.Osztaly", "Osztaly")
                        .WithMany("Tanulo")
                        .HasForeignKey("osztalyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Osztaly");
                });

            modelBuilder.Entity("_18_EF_EgyATobbKapcsolat.Osztaly", b =>
                {
                    b.Navigation("Tanulo");
                });
#pragma warning restore 612, 618
        }
    }
}
